// Auto-generated: UnicodeCase_special.hpp
// Generated by scripts/generate_unicode_case.py

#pragma once
#include <cstdint>
#include <cstddef>

namespace UnicodeCase {

struct SpecialEntry { uint32_t cp; const uint32_t* lower; std::size_t lower_len; const uint32_t* upper; std::size_t upper_len; const char* condition; };

static constexpr uint32_t SLOW_0[] = { 0x00DF };
static constexpr uint32_t SUP_0[] = { 0x0053, 0x0053 };
static constexpr uint32_t SLOW_1[] = { 0x0069, 0x0307 };
static constexpr uint32_t SUP_1[] = { 0x0130 };
static constexpr uint32_t SLOW_2[] = { 0xFB00 };
static constexpr uint32_t SUP_2[] = { 0x0046, 0x0046 };
static constexpr uint32_t SLOW_3[] = { 0xFB01 };
static constexpr uint32_t SUP_3[] = { 0x0046, 0x0049 };
static constexpr uint32_t SLOW_4[] = { 0xFB02 };
static constexpr uint32_t SUP_4[] = { 0x0046, 0x004C };
static constexpr uint32_t SLOW_5[] = { 0xFB03 };
static constexpr uint32_t SUP_5[] = { 0x0046, 0x0046, 0x0049 };
static constexpr uint32_t SLOW_6[] = { 0xFB04 };
static constexpr uint32_t SUP_6[] = { 0x0046, 0x0046, 0x004C };
static constexpr uint32_t SLOW_7[] = { 0xFB05 };
static constexpr uint32_t SUP_7[] = { 0x0053, 0x0054 };
static constexpr uint32_t SLOW_8[] = { 0xFB06 };
static constexpr uint32_t SUP_8[] = { 0x0053, 0x0054 };
static constexpr uint32_t SLOW_9[] = { 0x0587 };
static constexpr uint32_t SUP_9[] = { 0x0535, 0x0552 };
static constexpr uint32_t SLOW_10[] = { 0xFB13 };
static constexpr uint32_t SUP_10[] = { 0x0544, 0x0546 };
static constexpr uint32_t SLOW_11[] = { 0xFB14 };
static constexpr uint32_t SUP_11[] = { 0x0544, 0x0535 };
static constexpr uint32_t SLOW_12[] = { 0xFB15 };
static constexpr uint32_t SUP_12[] = { 0x0544, 0x053B };
static constexpr uint32_t SLOW_13[] = { 0xFB16 };
static constexpr uint32_t SUP_13[] = { 0x054E, 0x0546 };
static constexpr uint32_t SLOW_14[] = { 0xFB17 };
static constexpr uint32_t SUP_14[] = { 0x0544, 0x053D };
static constexpr uint32_t SLOW_15[] = { 0x0149 };
static constexpr uint32_t SUP_15[] = { 0x02BC, 0x004E };
static constexpr uint32_t SLOW_16[] = { 0x0390 };
static constexpr uint32_t SUP_16[] = { 0x0399, 0x0308, 0x0301 };
static constexpr uint32_t SLOW_17[] = { 0x03B0 };
static constexpr uint32_t SUP_17[] = { 0x03A5, 0x0308, 0x0301 };
static constexpr uint32_t SLOW_18[] = { 0x01F0 };
static constexpr uint32_t SUP_18[] = { 0x004A, 0x030C };
static constexpr uint32_t SLOW_19[] = { 0x1E96 };
static constexpr uint32_t SUP_19[] = { 0x0048, 0x0331 };
static constexpr uint32_t SLOW_20[] = { 0x1E97 };
static constexpr uint32_t SUP_20[] = { 0x0054, 0x0308 };
static constexpr uint32_t SLOW_21[] = { 0x1E98 };
static constexpr uint32_t SUP_21[] = { 0x0057, 0x030A };
static constexpr uint32_t SLOW_22[] = { 0x1E99 };
static constexpr uint32_t SUP_22[] = { 0x0059, 0x030A };
static constexpr uint32_t SLOW_23[] = { 0x1E9A };
static constexpr uint32_t SUP_23[] = { 0x0041, 0x02BE };
static constexpr uint32_t SLOW_24[] = { 0x1F50 };
static constexpr uint32_t SUP_24[] = { 0x03A5, 0x0313 };
static constexpr uint32_t SLOW_25[] = { 0x1F52 };
static constexpr uint32_t SUP_25[] = { 0x03A5, 0x0313, 0x0300 };
static constexpr uint32_t SLOW_26[] = { 0x1F54 };
static constexpr uint32_t SUP_26[] = { 0x03A5, 0x0313, 0x0301 };
static constexpr uint32_t SLOW_27[] = { 0x1F56 };
static constexpr uint32_t SUP_27[] = { 0x03A5, 0x0313, 0x0342 };
static constexpr uint32_t SLOW_28[] = { 0x1FB6 };
static constexpr uint32_t SUP_28[] = { 0x0391, 0x0342 };
static constexpr uint32_t SLOW_29[] = { 0x1FC6 };
static constexpr uint32_t SUP_29[] = { 0x0397, 0x0342 };
static constexpr uint32_t SLOW_30[] = { 0x1FD2 };
static constexpr uint32_t SUP_30[] = { 0x0399, 0x0308, 0x0300 };
static constexpr uint32_t SLOW_31[] = { 0x1FD3 };
static constexpr uint32_t SUP_31[] = { 0x0399, 0x0308, 0x0301 };
static constexpr uint32_t SLOW_32[] = { 0x1FD6 };
static constexpr uint32_t SUP_32[] = { 0x0399, 0x0342 };
static constexpr uint32_t SLOW_33[] = { 0x1FD7 };
static constexpr uint32_t SUP_33[] = { 0x0399, 0x0308, 0x0342 };
static constexpr uint32_t SLOW_34[] = { 0x1FE2 };
static constexpr uint32_t SUP_34[] = { 0x03A5, 0x0308, 0x0300 };
static constexpr uint32_t SLOW_35[] = { 0x1FE3 };
static constexpr uint32_t SUP_35[] = { 0x03A5, 0x0308, 0x0301 };
static constexpr uint32_t SLOW_36[] = { 0x1FE4 };
static constexpr uint32_t SUP_36[] = { 0x03A1, 0x0313 };
static constexpr uint32_t SLOW_37[] = { 0x1FE6 };
static constexpr uint32_t SUP_37[] = { 0x03A5, 0x0342 };
static constexpr uint32_t SLOW_38[] = { 0x1FE7 };
static constexpr uint32_t SUP_38[] = { 0x03A5, 0x0308, 0x0342 };
static constexpr uint32_t SLOW_39[] = { 0x1FF6 };
static constexpr uint32_t SUP_39[] = { 0x03A9, 0x0342 };
static constexpr uint32_t SLOW_40[] = { 0x1F80 };
static constexpr uint32_t SUP_40[] = { 0x1F08, 0x0399 };
static constexpr uint32_t SLOW_41[] = { 0x1F81 };
static constexpr uint32_t SUP_41[] = { 0x1F09, 0x0399 };
static constexpr uint32_t SLOW_42[] = { 0x1F82 };
static constexpr uint32_t SUP_42[] = { 0x1F0A, 0x0399 };
static constexpr uint32_t SLOW_43[] = { 0x1F83 };
static constexpr uint32_t SUP_43[] = { 0x1F0B, 0x0399 };
static constexpr uint32_t SLOW_44[] = { 0x1F84 };
static constexpr uint32_t SUP_44[] = { 0x1F0C, 0x0399 };
static constexpr uint32_t SLOW_45[] = { 0x1F85 };
static constexpr uint32_t SUP_45[] = { 0x1F0D, 0x0399 };
static constexpr uint32_t SLOW_46[] = { 0x1F86 };
static constexpr uint32_t SUP_46[] = { 0x1F0E, 0x0399 };
static constexpr uint32_t SLOW_47[] = { 0x1F87 };
static constexpr uint32_t SUP_47[] = { 0x1F0F, 0x0399 };
static constexpr uint32_t SLOW_48[] = { 0x1F80 };
static constexpr uint32_t SUP_48[] = { 0x1F08, 0x0399 };
static constexpr uint32_t SLOW_49[] = { 0x1F81 };
static constexpr uint32_t SUP_49[] = { 0x1F09, 0x0399 };
static constexpr uint32_t SLOW_50[] = { 0x1F82 };
static constexpr uint32_t SUP_50[] = { 0x1F0A, 0x0399 };
static constexpr uint32_t SLOW_51[] = { 0x1F83 };
static constexpr uint32_t SUP_51[] = { 0x1F0B, 0x0399 };
static constexpr uint32_t SLOW_52[] = { 0x1F84 };
static constexpr uint32_t SUP_52[] = { 0x1F0C, 0x0399 };
static constexpr uint32_t SLOW_53[] = { 0x1F85 };
static constexpr uint32_t SUP_53[] = { 0x1F0D, 0x0399 };
static constexpr uint32_t SLOW_54[] = { 0x1F86 };
static constexpr uint32_t SUP_54[] = { 0x1F0E, 0x0399 };
static constexpr uint32_t SLOW_55[] = { 0x1F87 };
static constexpr uint32_t SUP_55[] = { 0x1F0F, 0x0399 };
static constexpr uint32_t SLOW_56[] = { 0x1F90 };
static constexpr uint32_t SUP_56[] = { 0x1F28, 0x0399 };
static constexpr uint32_t SLOW_57[] = { 0x1F91 };
static constexpr uint32_t SUP_57[] = { 0x1F29, 0x0399 };
static constexpr uint32_t SLOW_58[] = { 0x1F92 };
static constexpr uint32_t SUP_58[] = { 0x1F2A, 0x0399 };
static constexpr uint32_t SLOW_59[] = { 0x1F93 };
static constexpr uint32_t SUP_59[] = { 0x1F2B, 0x0399 };
static constexpr uint32_t SLOW_60[] = { 0x1F94 };
static constexpr uint32_t SUP_60[] = { 0x1F2C, 0x0399 };
static constexpr uint32_t SLOW_61[] = { 0x1F95 };
static constexpr uint32_t SUP_61[] = { 0x1F2D, 0x0399 };
static constexpr uint32_t SLOW_62[] = { 0x1F96 };
static constexpr uint32_t SUP_62[] = { 0x1F2E, 0x0399 };
static constexpr uint32_t SLOW_63[] = { 0x1F97 };
static constexpr uint32_t SUP_63[] = { 0x1F2F, 0x0399 };
static constexpr uint32_t SLOW_64[] = { 0x1F90 };
static constexpr uint32_t SUP_64[] = { 0x1F28, 0x0399 };
static constexpr uint32_t SLOW_65[] = { 0x1F91 };
static constexpr uint32_t SUP_65[] = { 0x1F29, 0x0399 };
static constexpr uint32_t SLOW_66[] = { 0x1F92 };
static constexpr uint32_t SUP_66[] = { 0x1F2A, 0x0399 };
static constexpr uint32_t SLOW_67[] = { 0x1F93 };
static constexpr uint32_t SUP_67[] = { 0x1F2B, 0x0399 };
static constexpr uint32_t SLOW_68[] = { 0x1F94 };
static constexpr uint32_t SUP_68[] = { 0x1F2C, 0x0399 };
static constexpr uint32_t SLOW_69[] = { 0x1F95 };
static constexpr uint32_t SUP_69[] = { 0x1F2D, 0x0399 };
static constexpr uint32_t SLOW_70[] = { 0x1F96 };
static constexpr uint32_t SUP_70[] = { 0x1F2E, 0x0399 };
static constexpr uint32_t SLOW_71[] = { 0x1F97 };
static constexpr uint32_t SUP_71[] = { 0x1F2F, 0x0399 };
static constexpr uint32_t SLOW_72[] = { 0x1FA0 };
static constexpr uint32_t SUP_72[] = { 0x1F68, 0x0399 };
static constexpr uint32_t SLOW_73[] = { 0x1FA1 };
static constexpr uint32_t SUP_73[] = { 0x1F69, 0x0399 };
static constexpr uint32_t SLOW_74[] = { 0x1FA2 };
static constexpr uint32_t SUP_74[] = { 0x1F6A, 0x0399 };
static constexpr uint32_t SLOW_75[] = { 0x1FA3 };
static constexpr uint32_t SUP_75[] = { 0x1F6B, 0x0399 };
static constexpr uint32_t SLOW_76[] = { 0x1FA4 };
static constexpr uint32_t SUP_76[] = { 0x1F6C, 0x0399 };
static constexpr uint32_t SLOW_77[] = { 0x1FA5 };
static constexpr uint32_t SUP_77[] = { 0x1F6D, 0x0399 };
static constexpr uint32_t SLOW_78[] = { 0x1FA6 };
static constexpr uint32_t SUP_78[] = { 0x1F6E, 0x0399 };
static constexpr uint32_t SLOW_79[] = { 0x1FA7 };
static constexpr uint32_t SUP_79[] = { 0x1F6F, 0x0399 };
static constexpr uint32_t SLOW_80[] = { 0x1FA0 };
static constexpr uint32_t SUP_80[] = { 0x1F68, 0x0399 };
static constexpr uint32_t SLOW_81[] = { 0x1FA1 };
static constexpr uint32_t SUP_81[] = { 0x1F69, 0x0399 };
static constexpr uint32_t SLOW_82[] = { 0x1FA2 };
static constexpr uint32_t SUP_82[] = { 0x1F6A, 0x0399 };
static constexpr uint32_t SLOW_83[] = { 0x1FA3 };
static constexpr uint32_t SUP_83[] = { 0x1F6B, 0x0399 };
static constexpr uint32_t SLOW_84[] = { 0x1FA4 };
static constexpr uint32_t SUP_84[] = { 0x1F6C, 0x0399 };
static constexpr uint32_t SLOW_85[] = { 0x1FA5 };
static constexpr uint32_t SUP_85[] = { 0x1F6D, 0x0399 };
static constexpr uint32_t SLOW_86[] = { 0x1FA6 };
static constexpr uint32_t SUP_86[] = { 0x1F6E, 0x0399 };
static constexpr uint32_t SLOW_87[] = { 0x1FA7 };
static constexpr uint32_t SUP_87[] = { 0x1F6F, 0x0399 };
static constexpr uint32_t SLOW_88[] = { 0x1FB3 };
static constexpr uint32_t SUP_88[] = { 0x0391, 0x0399 };
static constexpr uint32_t SLOW_89[] = { 0x1FB3 };
static constexpr uint32_t SUP_89[] = { 0x0391, 0x0399 };
static constexpr uint32_t SLOW_90[] = { 0x1FC3 };
static constexpr uint32_t SUP_90[] = { 0x0397, 0x0399 };
static constexpr uint32_t SLOW_91[] = { 0x1FC3 };
static constexpr uint32_t SUP_91[] = { 0x0397, 0x0399 };
static constexpr uint32_t SLOW_92[] = { 0x1FF3 };
static constexpr uint32_t SUP_92[] = { 0x03A9, 0x0399 };
static constexpr uint32_t SLOW_93[] = { 0x1FF3 };
static constexpr uint32_t SUP_93[] = { 0x03A9, 0x0399 };
static constexpr uint32_t SLOW_94[] = { 0x1FB2 };
static constexpr uint32_t SUP_94[] = { 0x1FBA, 0x0399 };
static constexpr uint32_t SLOW_95[] = { 0x1FB4 };
static constexpr uint32_t SUP_95[] = { 0x0386, 0x0399 };
static constexpr uint32_t SLOW_96[] = { 0x1FC2 };
static constexpr uint32_t SUP_96[] = { 0x1FCA, 0x0399 };
static constexpr uint32_t SLOW_97[] = { 0x1FC4 };
static constexpr uint32_t SUP_97[] = { 0x0389, 0x0399 };
static constexpr uint32_t SLOW_98[] = { 0x1FF2 };
static constexpr uint32_t SUP_98[] = { 0x1FFA, 0x0399 };
static constexpr uint32_t SLOW_99[] = { 0x1FF4 };
static constexpr uint32_t SUP_99[] = { 0x038F, 0x0399 };
static constexpr uint32_t SLOW_100[] = { 0x1FB7 };
static constexpr uint32_t SUP_100[] = { 0x0391, 0x0342, 0x0399 };
static constexpr uint32_t SLOW_101[] = { 0x1FC7 };
static constexpr uint32_t SUP_101[] = { 0x0397, 0x0342, 0x0399 };
static constexpr uint32_t SLOW_102[] = { 0x1FF7 };
static constexpr uint32_t SUP_102[] = { 0x03A9, 0x0342, 0x0399 };
static constexpr uint32_t SLOW_103[] = { 0x03C2 };
static constexpr uint32_t SUP_103[] = { 0x03A3 };
static constexpr uint32_t SLOW_104[] = { 0x0307 };
static constexpr uint32_t SUP_104[] = { 0xFFFFFFFF };
static constexpr uint32_t SLOW_105[] = { 0x0069, 0x0307 };
static constexpr uint32_t SUP_105[] = { 0x0049 };
static constexpr uint32_t SLOW_106[] = { 0x006A, 0x0307 };
static constexpr uint32_t SUP_106[] = { 0x004A };
static constexpr uint32_t SLOW_107[] = { 0x012F, 0x0307 };
static constexpr uint32_t SUP_107[] = { 0x012E };
static constexpr uint32_t SLOW_108[] = { 0x0069, 0x0307, 0x0300 };
static constexpr uint32_t SUP_108[] = { 0x00CC };
static constexpr uint32_t SLOW_109[] = { 0x0069, 0x0307, 0x0301 };
static constexpr uint32_t SUP_109[] = { 0x00CD };
static constexpr uint32_t SLOW_110[] = { 0x0069, 0x0307, 0x0303 };
static constexpr uint32_t SUP_110[] = { 0x0128 };
static constexpr uint32_t SLOW_111[] = { 0x0069 };
static constexpr uint32_t SUP_111[] = { 0x0130 };
static constexpr uint32_t SLOW_112[] = { 0x0069 };
static constexpr uint32_t SUP_112[] = { 0x0130 };
static constexpr uint32_t SLOW_113[] = { 0xFFFFFFFF };
static constexpr uint32_t SUP_113[] = { 0x0307 };
static constexpr uint32_t SLOW_114[] = { 0xFFFFFFFF };
static constexpr uint32_t SUP_114[] = { 0x0307 };
static constexpr uint32_t SLOW_115[] = { 0x0131 };
static constexpr uint32_t SUP_115[] = { 0x0049 };
static constexpr uint32_t SLOW_116[] = { 0x0131 };
static constexpr uint32_t SUP_116[] = { 0x0049 };
static constexpr uint32_t SLOW_117[] = { 0x0069 };
static constexpr uint32_t SUP_117[] = { 0x0130 };
static constexpr uint32_t SLOW_118[] = { 0x0069 };
static constexpr uint32_t SUP_118[] = { 0x0130 };

static constexpr SpecialEntry SPECIAL_ENTRIES[] = {
    { 0x00DF, SLOW_0, sizeof(SLOW_0)/sizeof(SLOW_0[0]), SUP_0, sizeof(SUP_0)/sizeof(SUP_0[0]), "" },
    { 0x0130, SLOW_1, sizeof(SLOW_1)/sizeof(SLOW_1[0]), SUP_1, sizeof(SUP_1)/sizeof(SUP_1[0]), "" },
    { 0xFB00, SLOW_2, sizeof(SLOW_2)/sizeof(SLOW_2[0]), SUP_2, sizeof(SUP_2)/sizeof(SUP_2[0]), "" },
    { 0xFB01, SLOW_3, sizeof(SLOW_3)/sizeof(SLOW_3[0]), SUP_3, sizeof(SUP_3)/sizeof(SUP_3[0]), "" },
    { 0xFB02, SLOW_4, sizeof(SLOW_4)/sizeof(SLOW_4[0]), SUP_4, sizeof(SUP_4)/sizeof(SUP_4[0]), "" },
    { 0xFB03, SLOW_5, sizeof(SLOW_5)/sizeof(SLOW_5[0]), SUP_5, sizeof(SUP_5)/sizeof(SUP_5[0]), "" },
    { 0xFB04, SLOW_6, sizeof(SLOW_6)/sizeof(SLOW_6[0]), SUP_6, sizeof(SUP_6)/sizeof(SUP_6[0]), "" },
    { 0xFB05, SLOW_7, sizeof(SLOW_7)/sizeof(SLOW_7[0]), SUP_7, sizeof(SUP_7)/sizeof(SUP_7[0]), "" },
    { 0xFB06, SLOW_8, sizeof(SLOW_8)/sizeof(SLOW_8[0]), SUP_8, sizeof(SUP_8)/sizeof(SUP_8[0]), "" },
    { 0x0587, SLOW_9, sizeof(SLOW_9)/sizeof(SLOW_9[0]), SUP_9, sizeof(SUP_9)/sizeof(SUP_9[0]), "" },
    { 0xFB13, SLOW_10, sizeof(SLOW_10)/sizeof(SLOW_10[0]), SUP_10, sizeof(SUP_10)/sizeof(SUP_10[0]), "" },
    { 0xFB14, SLOW_11, sizeof(SLOW_11)/sizeof(SLOW_11[0]), SUP_11, sizeof(SUP_11)/sizeof(SUP_11[0]), "" },
    { 0xFB15, SLOW_12, sizeof(SLOW_12)/sizeof(SLOW_12[0]), SUP_12, sizeof(SUP_12)/sizeof(SUP_12[0]), "" },
    { 0xFB16, SLOW_13, sizeof(SLOW_13)/sizeof(SLOW_13[0]), SUP_13, sizeof(SUP_13)/sizeof(SUP_13[0]), "" },
    { 0xFB17, SLOW_14, sizeof(SLOW_14)/sizeof(SLOW_14[0]), SUP_14, sizeof(SUP_14)/sizeof(SUP_14[0]), "" },
    { 0x0149, SLOW_15, sizeof(SLOW_15)/sizeof(SLOW_15[0]), SUP_15, sizeof(SUP_15)/sizeof(SUP_15[0]), "" },
    { 0x0390, SLOW_16, sizeof(SLOW_16)/sizeof(SLOW_16[0]), SUP_16, sizeof(SUP_16)/sizeof(SUP_16[0]), "" },
    { 0x03B0, SLOW_17, sizeof(SLOW_17)/sizeof(SLOW_17[0]), SUP_17, sizeof(SUP_17)/sizeof(SUP_17[0]), "" },
    { 0x01F0, SLOW_18, sizeof(SLOW_18)/sizeof(SLOW_18[0]), SUP_18, sizeof(SUP_18)/sizeof(SUP_18[0]), "" },
    { 0x1E96, SLOW_19, sizeof(SLOW_19)/sizeof(SLOW_19[0]), SUP_19, sizeof(SUP_19)/sizeof(SUP_19[0]), "" },
    { 0x1E97, SLOW_20, sizeof(SLOW_20)/sizeof(SLOW_20[0]), SUP_20, sizeof(SUP_20)/sizeof(SUP_20[0]), "" },
    { 0x1E98, SLOW_21, sizeof(SLOW_21)/sizeof(SLOW_21[0]), SUP_21, sizeof(SUP_21)/sizeof(SUP_21[0]), "" },
    { 0x1E99, SLOW_22, sizeof(SLOW_22)/sizeof(SLOW_22[0]), SUP_22, sizeof(SUP_22)/sizeof(SUP_22[0]), "" },
    { 0x1E9A, SLOW_23, sizeof(SLOW_23)/sizeof(SLOW_23[0]), SUP_23, sizeof(SUP_23)/sizeof(SUP_23[0]), "" },
    { 0x1F50, SLOW_24, sizeof(SLOW_24)/sizeof(SLOW_24[0]), SUP_24, sizeof(SUP_24)/sizeof(SUP_24[0]), "" },
    { 0x1F52, SLOW_25, sizeof(SLOW_25)/sizeof(SLOW_25[0]), SUP_25, sizeof(SUP_25)/sizeof(SUP_25[0]), "" },
    { 0x1F54, SLOW_26, sizeof(SLOW_26)/sizeof(SLOW_26[0]), SUP_26, sizeof(SUP_26)/sizeof(SUP_26[0]), "" },
    { 0x1F56, SLOW_27, sizeof(SLOW_27)/sizeof(SLOW_27[0]), SUP_27, sizeof(SUP_27)/sizeof(SUP_27[0]), "" },
    { 0x1FB6, SLOW_28, sizeof(SLOW_28)/sizeof(SLOW_28[0]), SUP_28, sizeof(SUP_28)/sizeof(SUP_28[0]), "" },
    { 0x1FC6, SLOW_29, sizeof(SLOW_29)/sizeof(SLOW_29[0]), SUP_29, sizeof(SUP_29)/sizeof(SUP_29[0]), "" },
    { 0x1FD2, SLOW_30, sizeof(SLOW_30)/sizeof(SLOW_30[0]), SUP_30, sizeof(SUP_30)/sizeof(SUP_30[0]), "" },
    { 0x1FD3, SLOW_31, sizeof(SLOW_31)/sizeof(SLOW_31[0]), SUP_31, sizeof(SUP_31)/sizeof(SUP_31[0]), "" },
    { 0x1FD6, SLOW_32, sizeof(SLOW_32)/sizeof(SLOW_32[0]), SUP_32, sizeof(SUP_32)/sizeof(SUP_32[0]), "" },
    { 0x1FD7, SLOW_33, sizeof(SLOW_33)/sizeof(SLOW_33[0]), SUP_33, sizeof(SUP_33)/sizeof(SUP_33[0]), "" },
    { 0x1FE2, SLOW_34, sizeof(SLOW_34)/sizeof(SLOW_34[0]), SUP_34, sizeof(SUP_34)/sizeof(SUP_34[0]), "" },
    { 0x1FE3, SLOW_35, sizeof(SLOW_35)/sizeof(SLOW_35[0]), SUP_35, sizeof(SUP_35)/sizeof(SUP_35[0]), "" },
    { 0x1FE4, SLOW_36, sizeof(SLOW_36)/sizeof(SLOW_36[0]), SUP_36, sizeof(SUP_36)/sizeof(SUP_36[0]), "" },
    { 0x1FE6, SLOW_37, sizeof(SLOW_37)/sizeof(SLOW_37[0]), SUP_37, sizeof(SUP_37)/sizeof(SUP_37[0]), "" },
    { 0x1FE7, SLOW_38, sizeof(SLOW_38)/sizeof(SLOW_38[0]), SUP_38, sizeof(SUP_38)/sizeof(SUP_38[0]), "" },
    { 0x1FF6, SLOW_39, sizeof(SLOW_39)/sizeof(SLOW_39[0]), SUP_39, sizeof(SUP_39)/sizeof(SUP_39[0]), "" },
    { 0x1F80, SLOW_40, sizeof(SLOW_40)/sizeof(SLOW_40[0]), SUP_40, sizeof(SUP_40)/sizeof(SUP_40[0]), "" },
    { 0x1F81, SLOW_41, sizeof(SLOW_41)/sizeof(SLOW_41[0]), SUP_41, sizeof(SUP_41)/sizeof(SUP_41[0]), "" },
    { 0x1F82, SLOW_42, sizeof(SLOW_42)/sizeof(SLOW_42[0]), SUP_42, sizeof(SUP_42)/sizeof(SUP_42[0]), "" },
    { 0x1F83, SLOW_43, sizeof(SLOW_43)/sizeof(SLOW_43[0]), SUP_43, sizeof(SUP_43)/sizeof(SUP_43[0]), "" },
    { 0x1F84, SLOW_44, sizeof(SLOW_44)/sizeof(SLOW_44[0]), SUP_44, sizeof(SUP_44)/sizeof(SUP_44[0]), "" },
    { 0x1F85, SLOW_45, sizeof(SLOW_45)/sizeof(SLOW_45[0]), SUP_45, sizeof(SUP_45)/sizeof(SUP_45[0]), "" },
    { 0x1F86, SLOW_46, sizeof(SLOW_46)/sizeof(SLOW_46[0]), SUP_46, sizeof(SUP_46)/sizeof(SUP_46[0]), "" },
    { 0x1F87, SLOW_47, sizeof(SLOW_47)/sizeof(SLOW_47[0]), SUP_47, sizeof(SUP_47)/sizeof(SUP_47[0]), "" },
    { 0x1F88, SLOW_48, sizeof(SLOW_48)/sizeof(SLOW_48[0]), SUP_48, sizeof(SUP_48)/sizeof(SUP_48[0]), "" },
    { 0x1F89, SLOW_49, sizeof(SLOW_49)/sizeof(SLOW_49[0]), SUP_49, sizeof(SUP_49)/sizeof(SUP_49[0]), "" },
    { 0x1F8A, SLOW_50, sizeof(SLOW_50)/sizeof(SLOW_50[0]), SUP_50, sizeof(SUP_50)/sizeof(SUP_50[0]), "" },
    { 0x1F8B, SLOW_51, sizeof(SLOW_51)/sizeof(SLOW_51[0]), SUP_51, sizeof(SUP_51)/sizeof(SUP_51[0]), "" },
    { 0x1F8C, SLOW_52, sizeof(SLOW_52)/sizeof(SLOW_52[0]), SUP_52, sizeof(SUP_52)/sizeof(SUP_52[0]), "" },
    { 0x1F8D, SLOW_53, sizeof(SLOW_53)/sizeof(SLOW_53[0]), SUP_53, sizeof(SUP_53)/sizeof(SUP_53[0]), "" },
    { 0x1F8E, SLOW_54, sizeof(SLOW_54)/sizeof(SLOW_54[0]), SUP_54, sizeof(SUP_54)/sizeof(SUP_54[0]), "" },
    { 0x1F8F, SLOW_55, sizeof(SLOW_55)/sizeof(SLOW_55[0]), SUP_55, sizeof(SUP_55)/sizeof(SUP_55[0]), "" },
    { 0x1F90, SLOW_56, sizeof(SLOW_56)/sizeof(SLOW_56[0]), SUP_56, sizeof(SUP_56)/sizeof(SUP_56[0]), "" },
    { 0x1F91, SLOW_57, sizeof(SLOW_57)/sizeof(SLOW_57[0]), SUP_57, sizeof(SUP_57)/sizeof(SUP_57[0]), "" },
    { 0x1F92, SLOW_58, sizeof(SLOW_58)/sizeof(SLOW_58[0]), SUP_58, sizeof(SUP_58)/sizeof(SUP_58[0]), "" },
    { 0x1F93, SLOW_59, sizeof(SLOW_59)/sizeof(SLOW_59[0]), SUP_59, sizeof(SUP_59)/sizeof(SUP_59[0]), "" },
    { 0x1F94, SLOW_60, sizeof(SLOW_60)/sizeof(SLOW_60[0]), SUP_60, sizeof(SUP_60)/sizeof(SUP_60[0]), "" },
    { 0x1F95, SLOW_61, sizeof(SLOW_61)/sizeof(SLOW_61[0]), SUP_61, sizeof(SUP_61)/sizeof(SUP_61[0]), "" },
    { 0x1F96, SLOW_62, sizeof(SLOW_62)/sizeof(SLOW_62[0]), SUP_62, sizeof(SUP_62)/sizeof(SUP_62[0]), "" },
    { 0x1F97, SLOW_63, sizeof(SLOW_63)/sizeof(SLOW_63[0]), SUP_63, sizeof(SUP_63)/sizeof(SUP_63[0]), "" },
    { 0x1F98, SLOW_64, sizeof(SLOW_64)/sizeof(SLOW_64[0]), SUP_64, sizeof(SUP_64)/sizeof(SUP_64[0]), "" },
    { 0x1F99, SLOW_65, sizeof(SLOW_65)/sizeof(SLOW_65[0]), SUP_65, sizeof(SUP_65)/sizeof(SUP_65[0]), "" },
    { 0x1F9A, SLOW_66, sizeof(SLOW_66)/sizeof(SLOW_66[0]), SUP_66, sizeof(SUP_66)/sizeof(SUP_66[0]), "" },
    { 0x1F9B, SLOW_67, sizeof(SLOW_67)/sizeof(SLOW_67[0]), SUP_67, sizeof(SUP_67)/sizeof(SUP_67[0]), "" },
    { 0x1F9C, SLOW_68, sizeof(SLOW_68)/sizeof(SLOW_68[0]), SUP_68, sizeof(SUP_68)/sizeof(SUP_68[0]), "" },
    { 0x1F9D, SLOW_69, sizeof(SLOW_69)/sizeof(SLOW_69[0]), SUP_69, sizeof(SUP_69)/sizeof(SUP_69[0]), "" },
    { 0x1F9E, SLOW_70, sizeof(SLOW_70)/sizeof(SLOW_70[0]), SUP_70, sizeof(SUP_70)/sizeof(SUP_70[0]), "" },
    { 0x1F9F, SLOW_71, sizeof(SLOW_71)/sizeof(SLOW_71[0]), SUP_71, sizeof(SUP_71)/sizeof(SUP_71[0]), "" },
    { 0x1FA0, SLOW_72, sizeof(SLOW_72)/sizeof(SLOW_72[0]), SUP_72, sizeof(SUP_72)/sizeof(SUP_72[0]), "" },
    { 0x1FA1, SLOW_73, sizeof(SLOW_73)/sizeof(SLOW_73[0]), SUP_73, sizeof(SUP_73)/sizeof(SUP_73[0]), "" },
    { 0x1FA2, SLOW_74, sizeof(SLOW_74)/sizeof(SLOW_74[0]), SUP_74, sizeof(SUP_74)/sizeof(SUP_74[0]), "" },
    { 0x1FA3, SLOW_75, sizeof(SLOW_75)/sizeof(SLOW_75[0]), SUP_75, sizeof(SUP_75)/sizeof(SUP_75[0]), "" },
    { 0x1FA4, SLOW_76, sizeof(SLOW_76)/sizeof(SLOW_76[0]), SUP_76, sizeof(SUP_76)/sizeof(SUP_76[0]), "" },
    { 0x1FA5, SLOW_77, sizeof(SLOW_77)/sizeof(SLOW_77[0]), SUP_77, sizeof(SUP_77)/sizeof(SUP_77[0]), "" },
    { 0x1FA6, SLOW_78, sizeof(SLOW_78)/sizeof(SLOW_78[0]), SUP_78, sizeof(SUP_78)/sizeof(SUP_78[0]), "" },
    { 0x1FA7, SLOW_79, sizeof(SLOW_79)/sizeof(SLOW_79[0]), SUP_79, sizeof(SUP_79)/sizeof(SUP_79[0]), "" },
    { 0x1FA8, SLOW_80, sizeof(SLOW_80)/sizeof(SLOW_80[0]), SUP_80, sizeof(SUP_80)/sizeof(SUP_80[0]), "" },
    { 0x1FA9, SLOW_81, sizeof(SLOW_81)/sizeof(SLOW_81[0]), SUP_81, sizeof(SUP_81)/sizeof(SUP_81[0]), "" },
    { 0x1FAA, SLOW_82, sizeof(SLOW_82)/sizeof(SLOW_82[0]), SUP_82, sizeof(SUP_82)/sizeof(SUP_82[0]), "" },
    { 0x1FAB, SLOW_83, sizeof(SLOW_83)/sizeof(SLOW_83[0]), SUP_83, sizeof(SUP_83)/sizeof(SUP_83[0]), "" },
    { 0x1FAC, SLOW_84, sizeof(SLOW_84)/sizeof(SLOW_84[0]), SUP_84, sizeof(SUP_84)/sizeof(SUP_84[0]), "" },
    { 0x1FAD, SLOW_85, sizeof(SLOW_85)/sizeof(SLOW_85[0]), SUP_85, sizeof(SUP_85)/sizeof(SUP_85[0]), "" },
    { 0x1FAE, SLOW_86, sizeof(SLOW_86)/sizeof(SLOW_86[0]), SUP_86, sizeof(SUP_86)/sizeof(SUP_86[0]), "" },
    { 0x1FAF, SLOW_87, sizeof(SLOW_87)/sizeof(SLOW_87[0]), SUP_87, sizeof(SUP_87)/sizeof(SUP_87[0]), "" },
    { 0x1FB3, SLOW_88, sizeof(SLOW_88)/sizeof(SLOW_88[0]), SUP_88, sizeof(SUP_88)/sizeof(SUP_88[0]), "" },
    { 0x1FBC, SLOW_89, sizeof(SLOW_89)/sizeof(SLOW_89[0]), SUP_89, sizeof(SUP_89)/sizeof(SUP_89[0]), "" },
    { 0x1FC3, SLOW_90, sizeof(SLOW_90)/sizeof(SLOW_90[0]), SUP_90, sizeof(SUP_90)/sizeof(SUP_90[0]), "" },
    { 0x1FCC, SLOW_91, sizeof(SLOW_91)/sizeof(SLOW_91[0]), SUP_91, sizeof(SUP_91)/sizeof(SUP_91[0]), "" },
    { 0x1FF3, SLOW_92, sizeof(SLOW_92)/sizeof(SLOW_92[0]), SUP_92, sizeof(SUP_92)/sizeof(SUP_92[0]), "" },
    { 0x1FFC, SLOW_93, sizeof(SLOW_93)/sizeof(SLOW_93[0]), SUP_93, sizeof(SUP_93)/sizeof(SUP_93[0]), "" },
    { 0x1FB2, SLOW_94, sizeof(SLOW_94)/sizeof(SLOW_94[0]), SUP_94, sizeof(SUP_94)/sizeof(SUP_94[0]), "" },
    { 0x1FB4, SLOW_95, sizeof(SLOW_95)/sizeof(SLOW_95[0]), SUP_95, sizeof(SUP_95)/sizeof(SUP_95[0]), "" },
    { 0x1FC2, SLOW_96, sizeof(SLOW_96)/sizeof(SLOW_96[0]), SUP_96, sizeof(SUP_96)/sizeof(SUP_96[0]), "" },
    { 0x1FC4, SLOW_97, sizeof(SLOW_97)/sizeof(SLOW_97[0]), SUP_97, sizeof(SUP_97)/sizeof(SUP_97[0]), "" },
    { 0x1FF2, SLOW_98, sizeof(SLOW_98)/sizeof(SLOW_98[0]), SUP_98, sizeof(SUP_98)/sizeof(SUP_98[0]), "" },
    { 0x1FF4, SLOW_99, sizeof(SLOW_99)/sizeof(SLOW_99[0]), SUP_99, sizeof(SUP_99)/sizeof(SUP_99[0]), "" },
    { 0x1FB7, SLOW_100, sizeof(SLOW_100)/sizeof(SLOW_100[0]), SUP_100, sizeof(SUP_100)/sizeof(SUP_100[0]), "" },
    { 0x1FC7, SLOW_101, sizeof(SLOW_101)/sizeof(SLOW_101[0]), SUP_101, sizeof(SUP_101)/sizeof(SUP_101[0]), "" },
    { 0x1FF7, SLOW_102, sizeof(SLOW_102)/sizeof(SLOW_102[0]), SUP_102, sizeof(SUP_102)/sizeof(SUP_102[0]), "" },
    { 0x03A3, SLOW_103, sizeof(SLOW_103)/sizeof(SLOW_103[0]), SUP_103, sizeof(SUP_103)/sizeof(SUP_103[0]), "Final_Sigma" },
    { 0x0307, SLOW_104, sizeof(SLOW_104)/sizeof(SLOW_104[0]), SUP_104, sizeof(SUP_104)/sizeof(SUP_104[0]), "lt After_Soft_Dotted" },
    { 0x0049, SLOW_105, sizeof(SLOW_105)/sizeof(SLOW_105[0]), SUP_105, sizeof(SUP_105)/sizeof(SUP_105[0]), "lt More_Above" },
    { 0x004A, SLOW_106, sizeof(SLOW_106)/sizeof(SLOW_106[0]), SUP_106, sizeof(SUP_106)/sizeof(SUP_106[0]), "lt More_Above" },
    { 0x012E, SLOW_107, sizeof(SLOW_107)/sizeof(SLOW_107[0]), SUP_107, sizeof(SUP_107)/sizeof(SUP_107[0]), "lt More_Above" },
    { 0x00CC, SLOW_108, sizeof(SLOW_108)/sizeof(SLOW_108[0]), SUP_108, sizeof(SUP_108)/sizeof(SUP_108[0]), "lt" },
    { 0x00CD, SLOW_109, sizeof(SLOW_109)/sizeof(SLOW_109[0]), SUP_109, sizeof(SUP_109)/sizeof(SUP_109[0]), "lt" },
    { 0x0128, SLOW_110, sizeof(SLOW_110)/sizeof(SLOW_110[0]), SUP_110, sizeof(SUP_110)/sizeof(SUP_110[0]), "lt" },
    { 0x0130, SLOW_111, sizeof(SLOW_111)/sizeof(SLOW_111[0]), SUP_111, sizeof(SUP_111)/sizeof(SUP_111[0]), "tr" },
    { 0x0130, SLOW_112, sizeof(SLOW_112)/sizeof(SLOW_112[0]), SUP_112, sizeof(SUP_112)/sizeof(SUP_112[0]), "az" },
    { 0x0307, SLOW_113, sizeof(SLOW_113)/sizeof(SLOW_113[0]), SUP_113, sizeof(SUP_113)/sizeof(SUP_113[0]), "tr After_I" },
    { 0x0307, SLOW_114, sizeof(SLOW_114)/sizeof(SLOW_114[0]), SUP_114, sizeof(SUP_114)/sizeof(SUP_114[0]), "az After_I" },
    { 0x0049, SLOW_115, sizeof(SLOW_115)/sizeof(SLOW_115[0]), SUP_115, sizeof(SUP_115)/sizeof(SUP_115[0]), "tr Not_Before_Dot" },
    { 0x0049, SLOW_116, sizeof(SLOW_116)/sizeof(SLOW_116[0]), SUP_116, sizeof(SUP_116)/sizeof(SUP_116[0]), "az Not_Before_Dot" },
    { 0x0069, SLOW_117, sizeof(SLOW_117)/sizeof(SLOW_117[0]), SUP_117, sizeof(SUP_117)/sizeof(SUP_117[0]), "tr" },
    { 0x0069, SLOW_118, sizeof(SLOW_118)/sizeof(SLOW_118[0]), SUP_118, sizeof(SUP_118)/sizeof(SUP_118[0]), "az" },
};

} // namespace UnicodeCase
